### ISSUE TITLE
GanttChart is non functional!

### ISSUE THREAD

**Issue by OnSive** [HTMLElements/smart-blazor#1]
The complete component is in the current state non functional - which could be at least pointed out!

- No documentation on how to use the component - you need to figure all out by yourself, like you can get the GanttChart isntance with the OnReady EventCallback
- You can not add task manual
- You can not use the events of the GanttChart object (which would have a propper eventhandler in comparison to the EventCallbacks of the component)
- JavaScript errors on a whole bunch of GanttChart object functions (f.e. .GetState())
- ...

Have you a working example with more then showing 10 tasks or are you really selling a non functional library for a huge amount of money?

**Comment by bmarkov** [comment]
Thank you for your opinion. Soon, we will add more demos and docs regarding Gantt with Blazor. Documentation is available on the website. As far as I understand you find it incomplete. We will try to improve it in the future. If the component does not suit your needs, we are sorry about that!
